kafka:
  emailTopic: "email-messages-topic"
  requestTasksTopic: "request-task-reports-topic"
  taskReportsTopic: "task-reports-topic"
cron:
  expression: "59 59 23 * * *"
spring:
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 100
      properties:
        enable:
          idempotence: true
    consumer:
      group-id: request-receiver
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          deserializer:
            value:
              delegate:
                class: org.springframework.kafka.support.serializer.JsonDeserializer
          json:
            trusted:
              packages: com.kosvad9.core