name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_push_to_registry:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      
    - name: Login to Docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract meta for task-scheduler
      id: meta-task-scheduler
      uses: docker/metadata-action@v3
      with:
        images: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO_NAME }}
        tags: task-scheduler
        labels: task-scheduler
        
    - name: Extract meta for mail-sender-service
      id: meta-mail-sender-service
      uses: docker/metadata-action@v3
      with:
        images: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO_NAME }}
        tags: mail-sender-service
        labels: mail-sender-service
        
    - name: Extract meta for scheduler-service
      id: meta-scheduler-service
      uses: docker/metadata-action@v3
      with:
        images: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO_NAME }}
        tags: scheduler-service
        labels: scheduler-service

    - name: build and push task-scheduler image    
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ steps.meta-task-scheduler.outputs.tags}}
        labels: ${{ steps.meta-task-scheduler.outputs.labels}}

    - name: build and push mail-sender-service image    
      uses: docker/build-push-action@v3
      with:
        context: ./mail-sender-service
        push: true
        tags: ${{ steps.meta-mail-sender-service.outputs.tags}}
        labels: ${{ steps.meta-mail-sender-service.outputs.labels}}
        
    - name: build and push scheduler-service image    
      uses: docker/build-push-action@v3
      with:
        context: ./scheduler-service
        push: true
        tags: ${{ steps.meta-scheduler-service.outputs.tags}}
        labels: ${{ steps.meta-scheduler-service.outputs.labels}}
